keys:
  - &user_t3u age1nsprt0asqmy9wmc09yffwy34hx5v2a6hvat0cnzvr8h03f8ymezqguqtmy
  - &shared_key age127yfl2v82srpnq9jm70gh4l57jgt6vj7znw8an70luguwk8jv94qatuqvc
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_t3u
      - *shared_key