{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.my.home.desktop.gaming;
in
{
  options.my.home.desktop.gaming = {
    enable = mkEnableOption "Gaming tools and optimizations";
    nvidiaOffload = {
      enable = mkEnableOption "NVIDIA PRIME offload launchers (requires nvidia-offload on the system)";
    };
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      mangohud_git
      protonup-qt
      heroic
      prismlauncher
      steam-run
      gamescope_git
    ];

    # NVIDIA PRIME offload: launch Steam on the discrete GPU.
    # `nvidia-offload` is generated by the nvidia hardware module when PRIME
    # offload is enabled. For per-game offloading, set the Steam launch option
    # to: nvidia-offload %command%  (optionally wrapped in gamescope -e --).
    # Note: xdg.desktopEntries is currently broken in this home-manager
    # (the removed `extraConfig` option is still evaluated for every entry),
    # so the .desktop file is shipped directly via xdg.dataFile instead.
    xdg.dataFile."applications/steam-nvidia.desktop" = lib.mkIf cfg.nvidiaOffload.enable {
      text = ''
        [Desktop Entry]
        Type=Application
        Name=Steam (NVIDIA)
        Comment=Launch Steam on the discrete NVIDIA GPU
        Exec=nvidia-offload steam
        Icon=steam
        Categories=Game;
        Terminal=false
      '';
    };

    home.shellAliases = lib.mkIf cfg.nvidiaOffload.enable {
      steam-nvidia = "nvidia-offload steam";
    };
  };
}
