{
  config,
  lib,
  pkgs,
  ...
}:

with lib;
let
  cfg = config.my.home.desktop.gaming;
in
{
  options.my.home.desktop.gaming = {
    enable = mkEnableOption "Gaming tools and optimizations";
    nvidiaOffload = {
      enable = mkEnableOption "NVIDIA PRIME offload launchers (requires nvidia-offload on the system)";
    };
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      mangohud_git
      protonup-qt
      heroic
      prismlauncher
      steam-run
      gamescope_git
    ];

    # NVIDIA PRIME offload launchers. `nvidia-offload` is generated by the
    # nvidia hardware module when PRIME offload is enabled; it sets the full
    # offload environment (OpenGL via __GLX_VENDOR_LIBRARY_NAME, Vulkan via
    # __VK_LAYER_NV_optimus), so every game launched through it lands on the
    # discrete GPU — including Minecraft's experimental Vulkan renderer.
    # Note: xdg.desktopEntries is currently broken in this home-manager
    # (the removed `extraConfig` option is still evaluated for every entry),
    # so .desktop files are shipped directly via xdg.dataFile instead.
    # The stock entries are overridden by file name so the launcher's default
    # action already uses the dGPU (no per-launch ceremony).
    xdg.dataFile = lib.mkIf cfg.nvidiaOffload.enable {
      "applications/steam-nvidia.desktop" = {
        text = ''
          [Desktop Entry]
          Type=Application
          Name=Steam (NVIDIA)
          Comment=Launch Steam on the discrete NVIDIA GPU
          Exec=nvidia-offload steam
          Icon=steam
          Categories=Game;
          Terminal=false
        '';
      };

      # Prism Launcher (Minecraft): override the stock entry so the game always
      # runs on the dGPU. Keeps the original MimeType/StartupWMClass so modpack
      # file associations and window matching still work.
      "applications/org.prismlauncher.PrismLauncher.desktop" = {
        text = ''
          [Desktop Entry]
          Version=1.0
          Name=Prism Launcher
          Comment=Discover, manage, and play Minecraft instances
          Type=Application
          Terminal=false
          Exec=nvidia-offload prismlauncher %U
          StartupNotify=true
          Icon=org.prismlauncher.PrismLauncher
          Categories=Game;ActionGame;AdventureGame;Simulation;PackageManager;
          Keywords=game;minecraft;mc;
          StartupWMClass=PrismLauncher
          MimeType=application/zip;application/x-modrinth-modpack+zip;x-scheme-handler/curseforge;x-scheme-handler/prismlauncher;
        '';
      };

      # Heroic Games Launcher (Epic/GOG/Amazon): same override so Wine/Proton
      # titles inherit the PRIME offload environment.
      "applications/com.heroicgameslauncher.hgl.desktop" = {
        text = ''
          [Desktop Entry]
          Name=Heroic Games Launcher
          Exec=nvidia-offload heroic %u
          Terminal=false
          SingleMainWindow=true
          Type=Application
          Icon=com.heroicgameslauncher.hgl
          StartupWMClass=heroic
          Comment=An Open Source Launcher for GOG, Epic Games and Amazon Games
          MimeType=x-scheme-handler/heroic;
          Categories=Game;
        '';
      };
    };

    home.shellAliases = lib.mkIf cfg.nvidiaOffload.enable {
      steam-nvidia = "nvidia-offload steam";
      prismlauncher-nvidia = "nvidia-offload prismlauncher";
      heroic-nvidia = "nvidia-offload heroic";
    };
  };
}
