# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gsit = {
    pname = "gsit";
    version = "3.5.1";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.5.1/GSit-3.5.1.jar";
      sha256 = "sha256-o2wDt366JzemoEeWo4B1jTCSeBoxHV0vU+ARH9tREUE=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.10.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.10.0/ViaBackwards-5.10.0.jar";
      sha256 = "sha256-EHprzgixZhOCuFkN98CrcUvFlnqTwbui1xUxRIaJzoI=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.10.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.10.0/ViaVersion-5.10.0.jar";
      sha256 = "sha256-qxN7YoKXIcjO08VU7ekEpsAvbRljwzsy19QyuyVge2A=";
    };
  };
}
