# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gsit = {
    pname = "gsit";
    version = "3.2.1";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.2.1/GSit-3.2.1.jar";
      sha256 = "sha256-U0JPzSrDu9iMskSSgAdACOKl5dNTC96iHXQ0zqNkO64=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.8.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.8.0/ViaBackwards-5.8.0.jar";
      sha256 = "sha256-63moYWUw9u9dPkifD0HRlI6N8l+p2UYSw7Vw7ve77xY=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.8.0";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.8.0/ViaVersion-5.8.0.jar";
      sha256 = "sha256-XJ/Sq5s9mF6RqY8/yYcqGBfT5iYKBmjGnXhu1LumsgI=";
    };
  };
}
