{ config, lib, pkgs, ... }:

with lib;
let
  cfg = config.my.home.desktop.niri;
in {
  config = mkIf cfg.enable {
    # Matugen: Automatic dynamic theming from wallpaper
    programs.matugen = {
      enable = true;
      settings = {
        # Watch wallpaper directory for changes
        watch = {
          enable = true;
          mode = "debounce";
          debounce_ms = 500;
        };

        # Template definitions
        templates = {
          "noctalia-colors" = {
            input = "${config.home.homeDirectory}/.config/noctalia/templates/colors.css.template";
            output = "${config.home.homeDirectory}/.cache/noctalia-generated/colors.css";
          };
          "discord-theme" = {
            input = "${config.home.homeDirectory}/.config/noctalia/templates/discord.css.template";
            output = "${config.home.homeDirectory}/.config/vesktop/themes/noctalia-generated.css";
          };
          "niri-config" = {
            input = "${config.home.homeDirectory}/.config/noctalia/templates/niri.kdl.template";
            output = "${config.home.homeDirectory}/.config/noctalia-generated/niri-colors.kdl";
          };
        };

        # Image source for color extraction
        image = {
          path = "${config.home.homeDirectory}/.config/niri/wallpaper";
        };

        # Color palette settings
        colors = {
          mode = "auto";
          scheme_kind = "dark";
        };
      };
    };

    # Ensure Matugen runs on login
    systemd.user.services.matugen-watch = {
      Unit = {
        Description = "Matugen dynamic theming watcher";
        After = [ "graphical-session-pre.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.matugen}/bin/matugen mocha -w '${config.home.homeDirectory}/.config/niri/wallpaper'";
        Restart = "always";
        RestartSec = 5;
      };
      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };

    # Create template directory
    home.file.".config/noctalia/templates/.keep".text = "";

    # Niri color template (for future dynamic Niri theming)
    xdg.configFile."noctalia/templates/niri.kdl.template".text = ''
      // Niri colors generated by Matugen
      colors {
        // Primary branding colors
        primary = { r = {{colors.primary.default.rgb.r}}; g = {{colors.primary.default.rgb.g}}; b = {{colors.primary.default.rgb.b}}; };
        on_primary = { r = {{colors.on_primary.default.rgb.r}}; g = {{colors.on_primary.default.rgb.g}}; b = {{colors.on_primary.default.rgb.b}}; };
        
        // Surface colors for UI elements
        surface = { r = {{colors.surface.default.rgb.r}}; g = {{colors.surface.default.rgb.g}}; b = {{colors.surface.default.rgb.b}}; };
        on_surface = { r = {{colors.on_surface.default.rgb.r}}; g = {{colors.on_surface.default.rgb.g}}; b = {{colors.on_surface.default.rgb.b}}; };
      }
    '';
  };
}
