# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gsit = {
    pname = "gsit";
    version = "3.1.1";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.1.1/GSit-3.1.1.jar";
      sha256 = "sha256-fHM05GM5hOzEpfZIZklaAubBJehUwQWaIeib5KHLjwA=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.7.1";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.7.1/ViaBackwards-5.7.1.jar";
      sha256 = "sha256-elB1xx7Chj7eEtpVN8AWH/i1x6eKPBCGpJYziZEaARs=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.7.1";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.7.1/ViaVersion-5.7.1.jar";
      sha256 = "sha256-e5s9WjhExO5bGJZjJ2ku5+aY5311a4sPt4XlOg+apKU=";
    };
  };
}
