# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  gsit = {
    pname = "gsit";
    version = "3.2.1";
    src = fetchurl {
      url = "https://github.com/Gecolay/GSit/releases/download/3.2.1/GSit-3.2.1.jar";
      sha256 = "sha256-U0JPzSrDu9iMskSSgAdACOKl5dNTC96iHXQ0zqNkO64=";
    };
  };
  lunachat = {
    pname = "lunachat";
    version = "v3.0.16";
    src = fetchurl {
      url = "https://github.com/ucchyocean/LunaChat/releases/download/v3.0.16/LunaChat.jar";
      sha256 = "sha256-k9A1ptno5uxcw8+mC9BoB0KWaop6ccS+APgpwjJzM2o=";
    };
  };
  viabackwards = {
    pname = "viabackwards";
    version = "5.7.2";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaBackwards/releases/download/5.7.2/ViaBackwards-5.7.2.jar";
      sha256 = "sha256-y/TOTcEysbzMwqu5Ym7Ri7G9EWyTAGV1Q0WCQbAQAPc=";
    };
  };
  viaversion = {
    pname = "viaversion";
    version = "5.7.2";
    src = fetchurl {
      url = "https://github.com/ViaVersion/ViaVersion/releases/download/5.7.2/ViaVersion-5.7.2.jar";
      sha256 = "sha256-RDChJ/bLIdelLsagel3MQ7ojWswGLIYzBhm43h1JWP0=";
    };
  };
}
