{
  config,
  pkgs,
  lib,
  ...
}:

with lib;
let
  cfg = config.my.services.minecraft;
  # Load the auto-generated plugin definitions
  plugins = pkgs.callPackage ../plugins/generated.nix { };
  lunachat = import ../plugins/lunachat.nix { };
in
{
  config = mkIf cfg.enable {
    services.minecraft-servers.servers.lobby = {
      enable = true;
      package = pkgs.paperServers.paper; # Attribute that always tracks the latest stable release

      jvmOpts = "-Xms512M -Xmx1G";

      serverProperties = {
        server-port = 25566;
        max-players = 30;
        online-mode = false; # false because Velocity handles authentication
        white-list = false;
        gamemode = "adventure";
        force-gamemode = true;
        difficulty = "peaceful";
        level-type = "flat";
        level-seed = "";
        # Superflat customization (air only, biome is the_void)
        generator-settings = "{\"layers\": [{\"block\": \"minecraft:air\", \"height\": 1}], \"biome\": \"minecraft:the_void\"}";
        generate-structures = false; # Do not generate structures
        spawn-monsters = false;
        spawn-animals = false;
        spawn-npcs = false;
        allow-flight = true;
      };

      symlinks = {
        "plugins/ViaVersion.jar" = plugins.viaversion.src;
        "plugins/ViaBackwards.jar" = plugins.viabackwards.src;
        "plugins/GSit.jar" = plugins.gsit.src;
        "plugins/LunaChat.jar" = plugins.lunachat.src;
        "velocity-forwarding.secret" = config.sops.secrets.minecraft_forwarding_secret.path;
      };

      files = {
        # Reference LunaChat's settings from the shared config
        "plugins/LunaChat/config.yml".value = lunachat.config.lunaChatConfig;
        "config/paper-world-defaults.yml".value = {
          entities = {
            spawning = {
              spawn-limits = {
                monsters = 0;
                animals = 0;
                water-animals = 0;
                water-ambient = 0;
                water-underground-creature = 0;
                axolotls = 0;
                ambient = 0;
              };
            };
          };
        };
      };
    };

    # Extend the service generated by nix-minecraft
    systemd.services.minecraft-server-lobby = {
      # Fix udev warning
      environment.LD_LIBRARY_PATH = "${lib.makeLibraryPath [ pkgs.udev ]}";

      preStart = ''
              # Check for a world/player data reset
              if [ -f ".reset_world" ]; then
                echo "Resetting world and player data as requested..."
                rm -rf world*
                rm -f usercache.json
                rm .reset_world
              fi

              # Prepare the config directory
              mkdir -p config
              
              # Read the sops secret
              SECRET=$(cat ${config.sops.secrets.minecraft_forwarding_secret.path})
              
              # If the config file is a symlink into the Nix store (or similar), it cannot
              # be rewritten, so remove/move it aside and place a real file instead
              if [ -L "config/paper-global.yml" ]; then
                rm "config/paper-global.yml"
              fi

              cat <<EOF > config/paper-global.yml
        # Fix global config version warning
        config-version: 31
        proxies:
          velocity:
            enabled: true
            online-mode: true
            secret: $SECRET
        EOF
              chown minecraft:minecraft config/paper-global.yml
              chmod 600 config/paper-global.yml
      '';
    };
  };
}
