name: Scheduled Auto Update

on:
  schedule:
    - cron: '0 19 * * *' # 04:00 JST
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/auto-update.yml'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          # Use a PAT if available to trigger other workflows on push
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@master
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run nvfetcher (Minecraft Plugins)
        run: |
          nix shell nixpkgs#nvfetcher --command bash -c "cd nixos/services/minecraft/plugins && nvfetcher -c nvfetcher.toml"

      - name: Nix Flake Update
        run: nix flake update

      - name: Validate Changes
        run: nix flake check --show-trace --accept-flake-config --all-systems

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@master
        with:
          commit_message: "chore(auto): update system and plugins"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          branch: main
